//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaksi()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public string idTransaksi { get; set; }
        public System.DateTime tanggalTransaksi { get; set; }
        public string statusTransaksi { get; set; }
        public string pembayaran { get; set; }
        public string statusPembayaran { get; set; }
        public string idUser { get; set; }
        public string idCustomer { get; set; }
        public decimal total { get; set; }
        public decimal paid { get; set; }
        public string idMenu { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        public virtual User User { get; set; }
    }
}
