//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string noReport { get; set; }
        public System.DateTime rangeStart { get; set; }
        public System.DateTime rangeEnd { get; set; }
        public string idTransaksi { get; set; }
    
        public virtual Transaksi Transaksi { get; set; }
    }
}
