//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran3
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemTransaksi
    {
        public int id { get; set; }
        public string idTransaksi { get; set; }
        public string idMenu { get; set; }
        public int qty { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Transaksi Transaksi { get; set; }
    }
}
