//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meja
    {
        public string noMeja { get; set; }
        public string Jenis { get; set; }
        public int Kapasitas { get; set; }
        public string Status { get; set; }
    }
}
